### ISSUE TITLE
Fix JIRA description

### ISSUE THREAD

**Issue by rbideau** [RoadieHQ/marketing-site#109]
Hi,

There is some typo in the [jira plugin page](https://roadie.io/backstage/plugins/jira/)

##### 1. Typo in the import statement

![image](https://user-images.githubusercontent.com/7304827/107973642-c0d6d300-6fb5-11eb-9d1d-bcb1610f979b.png)

Missing a coma after `JiraCard`

##### 2. Typo in the `X-Atlassian-Token` header

The value should be `nocheck` without a dash, per this anwser: https://community.atlassian.com/t5/Answers-Developer-Questions/Getting-past-XSRF-check-failures-when-attempting-to-post-to-Rest/qaq-p/522137#M59793

##### 3. csp policy

To access images from Jira, the backstage csp should be changes to allow `*.atlassian.net` (or the jira instance url) in `backend.csp.img-src`

---

Would you accept a PR to fix theses in [`content/plugins/descriptions/jira.yaml`](https://github.com/RoadieHQ/marketing-site/blob/3f26d0a31f7eea8bad16ab8694f042f81e12c983/content/plugins/descriptions/jira.yaml) ?

**Comment by dtuite** [comment]
@rbideau absolutely. Well spotted and thank you.
