### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/marketing-site#4]
- [ ]  Make an svg for the Roadie logo instead of a font
- [x]  Buy the fonts that were recommended and use them on the site.
- [x]  Move html files into content dir and load with transformer. Similar to how I'm doing with the YAML files.
- [x] Consolidate `typography-body` and `typography-content` and just style all text by default.
- [ ] Consolidate all the `Link` components.

**Comment by martina-if** [comment]
![matketing](https://user-images.githubusercontent.com/736631/96967738-4074f980-1510-11eb-848b-db4a77363270.png)

Not a big deal but the `<`, `...` and similar symbols have a background color that's different than the rest. It seems they are highlighted but I don't think that's necessary. Perhaps we can tweak the highlighting theme?

**Comment by dtuite** [comment]
@martina-if Sure. If I remember correctly, the CSS for highlighting code is in `src/head-loaded-styles.css`. The library we use for highlighting is called `prismjs`. There are a number of themes available.

Do you want to open a Clubhouse story for it so we can prfioritize the work against all the other stories? Then we can close this issue. The uncompleted SVG task will be handled by Bianca.
