### ISSUE TITLE
Incorrect screenshot on GitHub PRs marketing page.

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/marketing-site#52]
This shows the Security Insights plugin.

https://roadie.io/backstage/plugins/github-pull-requests/

**Comment by dtuite** [comment]
@martina-if I believe you misclick closed this in the standup this morning 😀

**Comment by martina-if** [comment]
Oh, sorry about that!

**Comment by dtuite** [comment]
I just checked [the public website](https://roadie.io/backstage/plugins/github-pull-requests) and this issue is still outstanding so I am moving the corresponding card on the Backstage Plugin Development board back to "Up next".

**Comment by mcalus3** [comment]
It's some kind of a gatsby bug with building images. When you open the site's source, you'll see that the image's src is `src="/static/c7a8e87fc6a64f52bf3d2a257210ed60/ee604/GitHub-Mark-120px-plus.png"`. This is incorrect, somehow the image's source is set after the logo image and that's the real reason why those two github plugins share the same cover image - they have the same icon (in fact, github actions also).
