### ISSUE TITLE
Attribute plugins to their respective owners

### ISSUE THREAD

**Issue by dtuite** [RoadieHQ/marketing-site#68]
The plugin directory should give credit to the original authors of each plugin where possible. The attribution should include a link. See the official Backstage plugin marketplace as [an example of how to do this](https://backstage.io/plugins).

**Comment by stefanalund** [comment]
Can you describe how you think this marketplace adds value/is different than the official one? Listing only the plugins developed by Roadie seems more reasonable in my view.

**Comment by dtuite** [comment]
@stefanalund 

> Can you describe how you think this marketplace adds value/is different than the official one?

It adds value because all positive content on the internet about Backstage serves to promote and grow awareness. As Backstage becomes more widely known, many websites will host content about various plugins. That's a good thing as it increases the total number of opportunities for people to learn about Backstage.

Practically speaking, it's different because each plugin in the directory has a dedicated landing page (like this one for [the AWS Lambda plugin](https://roadie.io/backstage/plugins/aws-lambda)). These pages can rank well in Google and help people to discover the Backstage plugins that are available. They also provide users with direct instructions to install a given plugin.

Over time, these specific pages will become more Roadie centric. There will be certain plugins which will not work with Roadie for example, and they may indicate that. There may (or may not) also be specific install instructions or limitations of use and we need places to indicate that to potential users.

**Comment by stefanalund** [comment]
Thanks for the clarification. I do think we should add dedicated landing pages for the Plugin Marketplace on backstage.io as well. In the meantime, clarifying who the original plugin author is helps remove the confusion.
