### ISSUE TITLE
Replacing the Spotify logo with the Backstage logo

### ISSUE THREAD

**Issue by iamrajiv** [RoadieHQ/marketing-site#82]
<img width="140" alt="Screenshot 2020-12-22 at 5 38 31 AM" src="https://user-images.githubusercontent.com/42106787/102833737-ef05bf80-4417-11eb-900a-1177e45807a1.png">

**Comment by iamrajiv** [comment]
@dtuite I want to work on this.

**Comment by dtuite** [comment]
@iamrajiv is there a Backstage icon available to use instead?

**Comment by iamrajiv** [comment]
@dtuite I have tested with this https://github.com/backstage/backstage/blob/master/microsite/static/img/favicon.svg and I think it looks fine
<img width="160" alt="Screenshot 2020-12-23 at 1 56 00 AM" src="https://user-images.githubusercontent.com/42106787/102930287-2466e780-44c2-11eb-83f4-d9209a5f6ac5.png">

**Comment by dtuite** [comment]
@iamrajiv That does look good.

I need to check with Spotify that we can copy their logo into our repo. Can you open a PR which makes this change please, since you seem to have done it locally at least?

**Comment by dtuite** [comment]
I have reached out to Spotify on Discord to ask about this.

**Comment by iamrajiv** [comment]
@dtuite So can we use it? Also, I have not tested this locally I just used the inspect element to test the SVG logo code. Can you help me where to add the SVG logo code?

**Comment by dtuite** [comment]
@iamrajiv Ah! I see. Two places will need an update: `src/components/SitewideHeader/HamburgerMenu.js` and `src/components/SitewideHeader/index.js`.

No response from Spotify yet but they're usually not online much over the weekend. It might take some time.

**Comment by dtuite** [comment]
@iamrajiv Still no response from Spotify. I think we can go ahead and do this and we can always roll it back if there's a problem. Please feel free to send a PR.
